<?php $configInfo = $this->getArtistConfigaration(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo isset($configInfo['page_title']) ? $configInfo['page_title'] : ''; ?></h1>
</div>
<?php echo isset($configInfo['short_description']) ? $configInfo['short_description'] : ''; ?>
<?php echo isset($configInfo['address']) ? $configInfo['address'] : ''; ?>
<form action="<?php echo $this->getFormAction(); ?>" id="applyForm" method="post">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Application Form') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <label for="contact-name">Name<em>*</em></label>
                <div class="input-box">
                    <input name="contact-name" id="contact-name" title="Name" value="" class="input-text required-entry" type="text" />
                </div>
            </li>
            <li class="fields">
                <label for="address">Address<em>*</em></label>
                <div class="input-box">
                    <input name="address" id="address" title="Address" value="" class="input-text required-entry" type="text" />
                </div>
            </li>
            <li class="fields">
                <label for="city">City<em>*</em></label>
                <div class="input-box">
                    <input name="city" id="city" title="City" value="" class="input-text required-entry" type="text" />
                </div>
            </li>
            <li class="fields">
                <label for="state">State<em>*</em></label>
                <div class="input-box">
                    <input name="state" id="state" title="State" value="" class="input-text required-entry" type="text" />
                </div>
            </li>
            <li class="fields">
                <label for="phone">Phone<em>*</em></label>
                <div class="input-box">
                    <input name="phone" id="phone" title="Name" value="" class="input-text required-entry" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="contact-email">Email<em>*</em></label>
                <div class="input-box">
                    <input name="contact-email" id="contact-email" title="Email" value="" class="input-text required-entry validate-email" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="band">Band Name<em>*</em></label>
                <div class="input-box">
                    <input name="band" id="band" title="Band Name" value="" class="input-text required-entry" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="website">Web Site</label>
                <div class="input-box">
                    <input name="website" id="website" title="Web Site" value="" class="input-text validate-url" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="years">Years w/band<em>*</em></label>
                <div class="input-box">
                    <input name="years" id="years" maxlength="4" title="Years w/band" value="" class="input-text required-entry validate-digits" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="band2">Other Bands if any</label>
                <div class="input-box">
                    <input name="band2" id="band2"  title="Years w/band" value="" class="input-text" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="tours">Upcoming Tour Dates</label>
                <div class="input-box">
                    <input name="tours" type="text" class="input-text validate-date"  id="tours">
                    <script type="text/javascript">
                        // <![CDATA[
                        Calendar.setup({
                            inputField : 'tours',
                            ifFormat : '%m/%e/%Y',
                            button : 'date_from_trig',
                            align : 'Bl',
                            singleClick : true
                        });
                        // ]]>
                   </script>

                </div>
            </li>

            <li class="fields">
                <label for="tv">Upcoming TV Dates</label>
                <div class="input-box">
                    <input name="tv" id="tv" value="" class="input-text" type="text">
                    <script type="text/javascript">// <![CDATA[
                        Calendar.setup({
                            inputField : 'tv',
                            ifFormat : '%m/%e/%Y',
                            button : 'date_from_trig',
                            align : 'Bl',
                            singleClick : true
                        });
                        // ]]>
                   </script>
                </div>
            </li>

            <li class="fields">
                <label for="tv">Videos in Rotation</label>
                <div class="input-box">
                    <input name="video" id="video" value="" class="input-text" type="text">
                </div>
            </li>

            <li class="fields">
                <label for="record">Record Label</label>
                <div class="input-box">
                    <input name="record" id="record" value="" class="input-text" type="text">
                </div>
            </li>

            <li><div style="height:5px;clear:both"></div></li>

            <li class="fields">
                <label for="labelcontact">Contact Person<em>*</em></label>
                <div class="input-box">
                    <input name="labelcontact" id="labelcontact" value="" class="input-text required-entry" type="text">
                </div>
            </li>

            <li class="fields">
                <label for="labelphone">Phone<em>*</em></label>
                <div class="input-box">
                    <input name="labelphone" id="labelphone" value="" class="input-text required-entry" type="text">
                </div>
            </li>

            <li class="fields">
                <label for="labelsite">Web Site</label>
                <div class="input-box">
                    <input name="labelsite" id="labelsite" title="Web Site" value="" class="input-text validate-url" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="current">Current Record</label>
                <div class="input-box">
                    <input name="current" id="current" title="Current Record" value="" class="input-text" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="release">Release Date</label>
                <div class="input-box">
                    <input name="release" id="release" title="Release Date" value="" class="input-text validate-date" type="text" />
                    <script type="text/javascript">// <![CDATA[
                        Calendar.setup({
                            inputField : 'release',
                            ifFormat : '%m/%e/%Y',
                            button : 'date_from_trig',
                            align : 'Bl',
                            singleClick : true
                        });
                        // ]]>
                   </script>
                </div>
            </li>

            <li class="fields">
                <label for="sold">Copies Sold</label>
                <div class="input-box">
                    <input name="sold" id="sold" title="Copies Sold" value="" class="input-text validate-digits" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="previous">Previous Records</label>
                <div class="input-box">
                    <input name="previous" id="previous" title="Copies Sold" value="" class="input-text" type="text" />
                </div>
            </li>

            <li><div style="height:5px;clear:both"></div></li>

            <li class="fields">
                <label for="management">Management</label>
                <div class="input-box">
                    <input name="management" id="management" title="Management" value="" class="input-text" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="managementperson">Contact Person</label>
                <div class="input-box">
                    <input name="managementperson" id="managementperson" title="Contact Person" value="" class="input-text" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="managementcontact">Phone</label>
                <div class="input-box">
                    <input name="managementcontact" id="managementcontact" title="Phone" value="" class="input-text" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="managementwebsite">Web Site</label>
                <div class="input-box">
                    <input name="managementwebsite" id="managementwebsite" title="Web Site" value="" class="input-text validate-url" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="referred">Referred by</label>
                <div class="input-box">
                    <input name="referred" id="referred" title="Referred by" value="" class="input-text" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="drum">Drums currently playing</label>
                <div class="input-box">
                    <input name="drum" id="drum"  title="Drums currently playing" value="" class="input-text" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="contract">Under Contract?</label>
                <div class="input-box">
                    <input name="contract" id="contract" title="Under Contract?" value="" class="input-text" type="text" />
                </div>
            </li>

            <li class="fields">
                <label for="deal">If Yes, describe your relationship/deal</label>
                <div class="input-box">
                    <input name="deal" id="deal" title="If Yes, describe your relationship/deal" value="" class="input-text" type="text" />
                </div>
            </li>

            <li class="wide">
                <label for="drumkit">Describe your drum kit needs/desires</label>
                <div class="input-box">
                    <textarea name="drumkit" cols="50" class="input-text" id="drumkit"></textarea>
                </div>
            </li>

            <li class="wide">
                <label for="comments">List other endorsements you have (include contact person and phone number)<em>*</em></label>
                <div class="input-box">
                    <textarea rows="5" cols="50" name="comments" id="comments" class="input-text required-entry"></textarea>
                </div>
                <p><em><strong>Please check that you filled out the form completely before submitting and CLICK SEND ONLY ONCE. You will not receive a confirmation but it has been sent!</strong></em><br>
            </li>

        </ul>
    </div>
 <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('artists')->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo Mage::helper('artists')->__('Submit') ?>" class="button">
            <span><span><?php echo Mage::helper('artists')->__('Submit') ?></span></span>
        </button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('applyForm', true);
//]]>
</script>
