<?php $jsUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>
<!--link rel="stylesheet" type="text/css" href="<?php echo $jsUrl.'banner/orbit-1.2.3.css'; ?>" />
<script type="text/javascript" src="<?php echo $jsUrl.'banner/jquery.orbit-1.2.3.min.js'; ?>"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {  
        jQuery('#featured').orbit({
            animation: 'fade', // fade, horizontal-slide, vertical-slide, horizontal-push
            animationSpeed: 600, // how fast animtions are
            timer: true, // true or false to have the timer
            advanceSpeed: 4000, // if timer is enabled, time between transitions
            pauseOnHover: false, // if you hover pauses the slider
            startClockOnMouseOut: true, // if clock should start on MouseOut
            startClockOnMouseOutAfter: 1000, // how long after MouseOut should the timer start again
            directionalNav: true, // manual advancing directional navs
            captions: true, // do you want captions?
            captionAnimation: 'fade', // fade, slideOpen, none
            captionAnimationSpeed: 600, // if so how quickly should they animate in
            bullets: true, // true or false to activate the bullet navigation
            bulletThumbs: false, // thumbnails for the bullets
            bulletThumbLocation: '', // location from this file where thumbs will be
			afterSlideChange: function(){} 	 // empty function 
        });
                                
    });
</script-->

<!-- Attach our CSS -->
<link rel="stylesheet" type="text/css" href="<?php echo $jsUrl.'banner/orbit-1.2.3.css'; ?>" />
<!-- Attach necessary JS -->
<script type="text/javascript" src="<?php echo $jsUrl.'banner/newbanner/jquery-1.7.1.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $jsUrl.'banner/newbanner/jquery.orbit-1.2.3.min.js'; ?>"></script>	
<!-- Run the plugin -->
<script type="text/javascript">
	jQuery(window).load(function() {
		jQuery('#featured').orbit({
            animation: 'fade', // fade, horizontal-slide, vertical-slide, horizontal-push
            animationSpeed: 600, // how fast animtions are
            timer: true, // true or false to have the timer
            advanceSpeed: 4000, // if timer is enabled, time between transitions
            pauseOnHover: false, // if you hover pauses the slider
            startClockOnMouseOut: true, // if clock should start on MouseOut
            startClockOnMouseOutAfter: 1000, // how long after MouseOut should the timer start again
            directionalNav: true, // manual advancing directional navs
            captions: true, // do you want captions?
            captionAnimation: 'fade', // fade, slideOpen, none
            captionAnimationSpeed: 600, // if so how quickly should they animate in
            bullets: true, // true or false to activate the bullet navigation
            bulletThumbs: false, // thumbnails for the bullets
            bulletThumbLocation: '', // location from this file where thumbs will be
			afterSlideChange: function(){} 	 // empty function 
        });
	});
</script>

<style>

#innerModulelist {
    
    background: none;
    margin: 0;
}

#modulelistOuter, .jcarousel-skin-tango {
    
    background: none;
}

#containerTop {
    
    padding: 0 10px;
    width: auto;
}
</style>

<?php
$categoryList = $this->getArtistCategory();
$columnCount = 3;
if ($categoryList->count()) :
   $bannerHtml = '';
   $listHtml = '';
   $i = 2;
   foreach($categoryList as $_category) :
   
        $class = '';
        if($i%$columnCount==0){
            $class = ' last';
        }
   
        $mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
        $url = Mage::getUrl('artists/index/list').'id/'.$_category->getId();
        $image = explode('/', $_category->getThumbnail());
        $resize = Mage::getModel('artists/resize');
        $resize->setImagePath('artists/category');
        $resize->setImageName($image[count($image)-1]);
        $thumbnail = $resize->getResizedUrl(232, 115);

        $listHtml .= '<div class="moduletable'.$class.'">
                          <h3>'.$_category->getCategoryName().'</h3>';
        $listHtml .= '<div class="imagebox">
                         <a href="'.$url.'">'.
                             '<img src="'.$thumbnail.'" alt="'.$_category->getCategoryName().'" width="232" height="115" />'
                         .'</a>
                      </div>';
        $listHtml .= '<p>'.substr($_category->getContent(), 0, 200).'</p>';
        //$listHtml .= '<a href="'.$url.'" class="link">view Now</a>
        
        $listHtml .= '</div>';
   
        $bannerHtml .= '
                            <a href="'.$url.'">'
                                .'<img src="'.$mediaUrl.$_category->getMainImage().'" alt="'.$_category->getCategoryName().'" width="1030" height="376" />'.
                            '</a>';
        $i++;
    endforeach;
    $bannerHtml .= '';
endif;
?>
<div id="slider-wrapper">
    <div id="featured">
        <?php //echo $bannerHtml; ?>
        <?php echo $this->getLayout()->createBlock('banner/banner')->setTemplate('banner/banner.phtml')->toHtml(); ?>   
    </div>
</div>

<div id="modulelistOuter">
    <div id="innerModulelist">
        <div class="moduleWrap clearfix">
            <div class="moduletable">
                <h3>FEATURED</h3>
                <div class="imagebox">
                     <a href="<?php echo $this->getUrl('artists/index/featured') ?>">
                         <?php
                         $thumbnailImage = Mage::getStoreConfig('catalog/placeholder/thumbnail_placeholder');
                        //Mage::helper(‘core/url’)->getHomeUrl();
                        if ($thumbnailImage) {
                        $thumbnail = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product/placeholder/'.$thumbnailImage;
                        } else {
                        //$thumbnail = Mage::getDesign()->getSkinUrl('images/catalog/product/placeholder/thumbnail.jpg');
				$thumbnail = Mage::getDesign()->getSkinUrl('images/featuredArtist_sm.jpg');
                        }
                          ?>
                        <img width="232" height="115" alt="US ARTISTS" src="<?php echo $thumbnail; ?>">
                     </a>
                </div>
                <p>FEATURED</p>
            </div>
            <?php echo $listHtml; ?>
        </div>
    </div>
</div>