<?php
$helper				= Mage::helper('lightboxes');
$rel                = $helper->getLightboxRel($helper->getConfig('lightbox_type'));
$class              = $helper->getLightboxClass($helper->getConfig('lightbox_type'));

$mainImageRel		= $rel;
$mainImageClass		= $class;
if($helper->getConfig('lightbox_type') == 'piroboxextended'){
	$mainImageRel	= 'single';
	$mainImageClass = 'pirobox';
}elseif($helper->getConfig('lightbox_type') == 'prettyphoto'){
	$mainImageRel	= 'prettyPhoto';
	$mainImageClass = '';
}elseif(!in_array($helper->getConfig('lightbox_type'),array('piroboxextended', 'prettyphoto'))){
	$mainImageRel	= $rel . '-main';
	$mainImageClass = $class . '-main';
}
?>

<!-- jQuery LightBoxes -->
    <?php if($helper->getConfig('include_jquery', 'lightboxes_confliction') && $helper->getConfig('include_jquery_in', 'lightboxes_confliction') == 'media'): 	?>
		<?php echo $this->getChildHtml('jquery_inclusion'); ?>
	<?php endif; ?>

    <?php if($helper->getConfig('include_lighboxes_in', 'lightboxes_confliction') == 'media'): ?>
		<?php echo $this->getChildHtml('lightboxes_inclusion'); ?>
	<?php endif; ?>

	<?php if($helper->getConfig('include_initialization_in', 'lightboxes_confliction') == 'media'): ?>
		<?php echo $this->getChildHtml('lightboxes_initialization'); ?>
	<?php endif; ?>
    
    
<?php if (strstr($_SERVER["REQUEST_URI"], 'artists/index/view/id')) { ?>
<!-- jQuery LightBoxes -->
<script type="text/javascript" src="<?php echo Mage::getUrl(''); ?>js/lightboxes/no-conflict.js"></script>	
<!-- Pirobox Extended -->
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getUrl(''); ?>js/lightboxes/pirobox_extended/css_pirobox/style_1/style.css" />
<script type="text/javascript" src="<?php echo Mage::getUrl(''); ?>js/lightboxes/pirobox_extended/js/jquery-ui-1.8.2.custom.min.js"></script>
<script type="text/javascript" src="<?php echo Mage::getUrl(''); ?>js/lightboxes/pirobox_extended/js/pirobox_extended_min.js"></script>
<!-- Pirobox -->
<!-- //jQuery LightBoxes -->    

<script type="text/javascript">
    jQuery(document).ready(function(){
       jQuery().piroBox_ext({
			piro_speed : 700,
            bg_alpha : 0.5,
            piro_scroll : 0
		});
    });
</script>

<?php } ?>

    
    
<!-- //jQuery LightBoxes -->

<div id="messages_product_view">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<?php
$artistInfo = $this->getArtistInformation();
$gallery = $this->getArtistGallery();
if ($artistInfo):
    $artist = array_pop($artistInfo);
?>

<div class="clearfix">
	<div id="contentCol">
		<div class="content">
            <div class="page-title artists">
    			<h2><?php echo $artist['title']; ?></h2>
            </div>
    		<h3 class="artists"><?php echo $artist['name']; ?></h3>
    		<div class="displayimage">
                            <?php
                            $resize = Mage::getModel('artists/resize');
                            $resize->setImagePath('artists');
                            if ($gallery):
                                $resize->setImageName($gallery[0]['image']);
                                $thumbnail = $resize->getResizedUrl(649, 371);
                            ?>
                            <a href="<?php echo $thumbnail; ?>" rel="<?php echo $rel; ?>" class="<?php echo $class; ?>" title="<?php echo $artist['title']; ?>">
                                <img src="<?php echo $thumbnail; ?>" width="649" height="371" alt="<?php echo $artist['title']; ?>" />
                            </a>
                            <?php endif; ?>
                                                        
                        </div>
                        <p><?php echo $artist['biography']; ?></p>
            <?php echo $artist['website']; ?>
            
            <br>
            
    		<div class="videoBox">
    			<h3>VIDEOS</h3>
    			<div class="box">
                    <?php echo $artist['video_url']; ?>
                </div>
            </div>
            
		</div>
	</div>
	<div id="rihgtCol">
                <?php
                 if ($gallery):
                     $_iterator = 1;
                 ?>
                    <div class="photoBox">
			<h3>Photos</h3>
                        <div class="box clearfix">
                            <?php 
                            foreach ($gallery as $photo):
                                $resize->setImageName($photo['image']);
                                $big_image = $resize->getResizedUrl(649, 371);
                                //$resize1 = $resize->keepAspectRatio(FALSE);
                                $thumbnail = $resize->getResizedUrl(127, 100);
                            ?>
				<div class="itembox <?php if ($_iterator%2==0) echo 'last'; ?>">
                    <a href="<?php echo $big_image; ?>" rel="<?php echo $rel; ?>" class="<?php echo $class; ?>" title="<?php echo $artist['title']; ?>">
                                    <img src="<?php echo $thumbnail; ?>" alt="" />
                    </a>
                                </div>
                                <?php if ($_iterator++%2==0): ?>
                                    </div><div class="box clearfix">
                                <?php endif; ?>
                            <?php endforeach; ?>
                                                       
                        </div>
                    </div>
                <?php endif; ?>
		<div class="configuration">
                    <?php echo $artist['configaration']; ?>
		</div>
	</div>
</div>
<?php endif; ?>


