<?php $sliders = $this->getSliderList(); ?>
<div class=" jcarousel-skin-tango">
      <ul id="mycarousel" class="jcarousel-list jcarousel-list-horizontal">
        <?php foreach ($sliders as $_slider): ?>
        <li>
            <h3><?php echo $_slider->getTitle(); ?></h3>
            <div class="imagebox">
		      <a href="<?php echo $_slider->getLink(); ?>">
        
                <?php
                 if($_slider->getImage() == ''){
                    $thumbnailImage = Mage::getStoreConfig('catalog/placeholder/thumbnail_placeholder');
                    //Mage::helper(‘core/url’)->getHomeUrl();
                    if ($thumbnailImage) {
                    $imageName = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product/placeholder/'.$thumbnailImage;
                    } else {
                    $imageName = Mage::getDesign()->getSkinUrl('images/catalog/product/placeholder/thumbnail.jpg');
                    }
                } else {
                    $imageName = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'slider/'.$_slider->getImage();
                }                
                ?>
        
                    <img src="<?php echo $imageName; ?>" alt="<?php echo $_slider->getTitle(); ?>" height="143" width="237">
                    
                </a>
            </div>
            <p><?php echo $_slider->getContent(); ?></p>
        </li>
       <?php endforeach; ?>
      </ul>
  </div>